os: linux
dist: jammy
language: python
python:
  - "3.10"

install:
  - sudo apt update
  - sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential cython3
  - pip install --upgrade pip setuptools wheel
  - pip install Cython==0.29.33 buildozer

script:
  - echo "Компилируем 32-битную версию..."
  - cp buildozer_32.spec buildozer.spec
  - yes | buildozer android debug
  - ls -la bin/
  - rm -rf .buildozer

  - echo "Компилируем 64-битную версию..."
  - cp buildozer_64.spec buildozer.spec
  - yes | buildozer android debug
  - ls -la bin/

deploy:
  - provider: releases
    api_key: $TOKENS
    file_glob: true
    file: "bin/*armeabi*.apk"
    skip_cleanup: true
    on:
      branch: main

  - provider: releases
    api_key: $TOKENS
    file_glob: true
    file: "bin/*arm64*.apk"
    skip_cleanup: true
    on:
      branch: main

cache:
  pip: true
  directories:
    - $HOME/.buildozer
    - $HOME/.gradle